Added factorization and seeders for data
HappyLlamas/LamaReader pull request #29
Opened 2022-10-09 11:10 UTC by txmxrxrxnxi

2022-10-09 11:36 UTC, lolpie244 requested changes

2022-10-09 11:36 UTC, lolpie244 commented on src/DataImport/Models/ReadingProgress.cs
> +	public ReadingProgress()
you can define default values for property, so there is no need in constructor

2022-10-09 11:36 UTC, lolpie244 commented on src/DataImport/Models/User.cs
> +		int id,
we don't need a constructor if we don't have additional logic. Better to use `new User(){field = value}`

2022-10-09 11:36 UTC, lolpie244 commented on src/DataImport/Utilities/Hashing.cs
> +		foreach (byte b in hash)
use `BitConverter.ToString(hash)`, instead foreach

2022-10-09 11:36 UTC, lolpie244 commented on src/DataImport/Utilities/Seeders.cs
> +	public static Book[] GetBooks()
Why do you separate books from other seeds?

2022-10-09 14:24 UTC, txmxrxrxnxi commented on src/DataImport/Utilities/Seeders.cs
> +	public static Book[] GetBooks()
Those are not random books, those are set ones with info from files

2022-10-09 14:29 UTC, txmxrxrxnxi commented on src/DataImport/Utilities/Hashing.cs
> +		foreach (byte b in hash)
+

2022-10-09 14:31 UTC, txmxrxrxnxi commented on src/DataImport/Models/User.cs
> +		int id,
`+

2022-10-09 20:40 UTC, lolpie244 commented on src/DataImport/Utilities/Seeders.cs
> +	public static Book[] GetBooks()
so what? Our other random data is also seeds. So it's better to not separate books and other seeds. You can move other "random" seeds into this file

2022-10-10 05:21 UTC, txmxrxrxnxi commented on src/DataImport/Models/ReadingProgress.cs
> +	public ReadingProgress()
`+

2022-10-10 05:22 UTC, txmxrxrxnxi commented on src/DataImport/Utilities/Seeders.cs
> +	public static Book[] GetBooks()
Random data are not the same the seeders are

2022-10-10 05:23 UTC, lolpie244 commented on src/DataImport/Utilities/Seeders.cs
> +	public static Book[] GetBooks()
Oh, yeah, I forgot about it

2022-10-10 05:24 UTC, lolpie244 approved these changes

2022-10-10 07:15 UTC, lolpie244 requested changes

2022-10-10 07:15 UTC, lolpie244 commented on src/DataImport/Factories/BookFactory.cs
> +	public int PagesNumber { get; } = RandomNumber.Next();
"UrlToFIle" field missing

2022-10-10 07:26 UTC, txmxrxrxnxi commented on src/DataImport/Factories/BookFactory.cs
> +	public int PagesNumber { get; } = RandomNumber.Next();
`+

2022-10-10 07:28 UTC, lolpie244 approved these changes

2022-10-10 07:28 UTC, Combo3zoom commented on src/DataImport/Models/Bookmark.cs
> +	public int BookId { get; set; }
change foreign key bookId and UserId to readingProgressId

2022-10-10 07:28 UTC, Combo3zoom commented on src/DataImport/Models/Bookmark.cs
> +	public string Note { get; set; }
delete prop Note we don't use him

2022-10-10 07:29 UTC, txmxrxrxnxi commented on src/DataImport/Models/Bookmark.cs
> +	public int BookId { get; set; }
`+

2022-10-10 07:31 UTC, txmxrxrxnxi commented on src/DataImport/Models/Bookmark.cs
> +	public string Note { get; set; }
`+

2022-10-10 07:49 UTC, lolpie244 commented on src/DataImport/Models/Bookmark.cs
> +	public string Note { get; set; }
no, we use note

2022-10-10 07:57 UTC, merged